services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    # Using tail -f /dev/null to keep container running
    command: python src/clean_up_mail.py
    # Alternative approach using restart policy
    restart: on-failure
