services:
  app:
    build: .
    volumes:
      - .:/app
    # Using tail -f /dev/null to keep container running
    command: sh -c "python src/clean_up_mail.py || true; tail -f /dev/null"
    # Alternative approach using restart policy
    restart: on-failure
